### PR TITLE
feat: add dockerignore file

### PR DESCRIPTION
**Pull request by muety**

### CODE REVIEW

**Comment by brentvollebregt** [comment]
Looking at the rule to ignore `*.db`, I have realised that when a one of these containers are deleted, the database is also. Could we add an externally mounted volume to stop this?

**Comment by brentvollebregt** [comment]
I see that at the moment, it's not easy to configure where the database file is located. I'll set up the config so we could use an environment variable.

**Comment by muety** [comment]
Yes, what I did for my running instance is move the database into data/data.db, then create a persistent, named Docker volume and mount it to /app/data.

Environment variables would be cool!

**Comment by fluential** [comment]
@muety @brentvollebregt check this https://github.com/brentvollebregt/hit-counter/pull/13 & https://github.com/brentvollebregt/hit-counter/issues/14

**Pull request merged**
